<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fcd37572-74b0-49c5-9d6a-69ed9a211813</elementGuidId>
    <imagePath></imagePath>
    <name>select_status</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-hs[1]/div[1]/section[1]/div[1]/app-hajj-screening-records[1]/div[3]/div[1]/div[1]/div[2]/div[3]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="col-md-3\\ col-sm-3\\ col-xs-12"]:nth-child(3) &gt; #status</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'status')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["div &gt;&gt; internal:has-text=/^ResultAllFit to perform hajjRequires further evaluationFailed health examination$/ &gt;&gt; #status"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>status</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
</WebElementEntity>