<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>661d5636-66ca-4c53-91db-01f13d0495ff</elementGuidId>
    <imagePath></imagePath>
    <name>button_start_health_examination</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-hajj-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/app-hajj-register-patient[1]/div[3]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-primary\\ px-4\\ mr-2"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Start Health Examination')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Continue Health Examination"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Start Health Examination</value>
        <webElementGuid>8cc58e3e-b39a-4497-ada5-dd3f2824e9e9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>8cc58e3e-b39a-4497-ada5-dd3f2824e9e9</webElementGuid>
    </webElementProperties>
</WebElementEntity>