<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4101da28-6cf6-4a80-8099-3578fc0cb392</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_appointment_desk</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-hs[1]/div[1]/app-sidebar[1]/section[1]/nav[1]/ul[1]/li[9]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="menu-item"]:nth-child(9) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Appointment Desk')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="Appointment Desk"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Appointment Desk</value>
        <webElementGuid>203a3707-bed2-4238-b87f-c355bcef998a</webElementGuid>
    </webElementProperties>
</WebElementEntity>