<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>81641b20-1754-4aa5-b8cb-01c1437bad43</elementGuidId>
    <imagePath></imagePath>
    <name>input_1_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-hajj-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/app-hajj-assessments[1]/div[1]/div[3]/div[1]/div[1]/span[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-check\\ form-check-inline\\ ng-star-inserted"]:nth-child(2) &gt; #\\31 \\.1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'1.1') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; [id="\\31 \\.1"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>1.1</value>
        <webElementGuid>8cc58e3e-b39a-4497-ada5-dd3f2824e9e9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>8cc58e3e-b39a-4497-ada5-dd3f2824e9e9</webElementGuid>
    </webElementProperties>
</WebElementEntity>