<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5bcceb22-c4f8-4215-8a05-5ab03b6b1bf4</elementGuidId>
    <imagePath></imagePath>
    <name>input_6_3_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[8]/form[1]/app-observation[1]/div[1]/div[3]/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="row\\ ml-4\\ ng-star-inserted"]:nth-child(2) &gt; #\\36 \\.3\\.1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'6.3.1') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="8"i &gt;&gt; div &gt;&gt; internal:has-text=/^Normal$/ &gt;&gt; internal:role=radio</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>6.3.1</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
</WebElementEntity>