<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d6021551-d297-4e6d-93e3-faf715632843</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[3]/form[1]/app-assessments[1]/div[1]/div[3]/div[2]/table[1]/tbody[1]/tr[2]/td[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="p-3\\ border\\ rounded\\ mt-3\\ mb-3\\ ng-star-inserted"]:nth-child(4) &gt; [class="radioTable"] [class="ng-star-inserted"]:nth-child(2) &gt; [class="ng-untouched\\ ng-pristine\\ ng-valid"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=row[name="Having little interest or"i] &gt;&gt; internal:role=radio &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
</WebElementEntity>