<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7b8d95e8-bc31-4604-8ae8-170658f2b3db</elementGuidId>
    <imagePath></imagePath>
    <name>label_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[1]/form[1]/app-register-patient[1]/div[1]/form[1]/div[1]/div[1]/div[10]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-group\\ row"]:nth-child(10) &gt; [class="col-sm-4\\ required"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Postcode:"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>