<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>36e51043-0f16-4c6b-b05e-a17b77261da5</elementGuidId>
    <imagePath></imagePath>
    <name>button_continue_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/community-hs[1]/div[1]/section[1]/app-health-screening[1]/div[3]/div[1]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>*:nth-child(4) *:nth-child(3) &gt; *:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Continue')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Continue"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Continue</value>
        <webElementGuid>8cc58e3e-b39a-4497-ada5-dd3f2824e9e9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>8cc58e3e-b39a-4497-ada5-dd3f2824e9e9</webElementGuid>
    </webElementProperties>
</WebElementEntity>