<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2d0a7535-3bf8-4d13-907b-89bacaf6e860</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/community-hs[1]/div[1]/section[1]/app-health-screening[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[2]/ng-select[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-select-container"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["div &gt;&gt; internal:has-text=/^Search and select for departments$/ &gt;&gt; nth=0"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>