<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ade34708-8123-4f5a-9bfd-dc9c6b8d804f</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_13</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[5]/form[1]/community-observation[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="col-md-4\\ ng-star-inserted"]:nth-child(1) [class="form-control\\ ng-untouched\\ ng-pristine\\ ng-valid"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'number')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["div &gt;&gt; internal:has-text=/^Blood Pressure\\\\(Systolic\\\\)mm/HgBlood Pressure\\\\(Diastolic\\\\)mm/HgPulse Ratebpm$/ &gt;&gt; internal:role=spinbutton &gt;&gt; nth=0"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>number</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
</WebElementEntity>