<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f45708c-e436-43dd-9e9c-6f4d85f62854</elementGuidId>
    <imagePath></imagePath>
    <name>input_1_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[2]/form[1]/community-assessments[1]/div[1]/div[2]/div[1]/div[1]/span[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-check\\ form-check-inline\\ ng-star-inserted"]:nth-child(2) &gt; #\\31 \\.1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'1.1') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=radio &gt;&gt; nth=1"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>1.1</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
</WebElementEntity>