<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ef0b3e75-6c8c-4d97-9099-4b94f45a1f75</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[1]/form[1]/community-register-patient[1]/div[1]/form[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-control\\ w-100\\ ng-untouched\\ ng-pristine\\ ng-invalid\\ ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder="Enter Identification Number"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>203a3707-bed2-4238-b87f-c355bcef998a</webElementGuid>
    </webElementProperties>
</WebElementEntity>