<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ddc8ddf3-b981-4724-91c3-8bfb702717da</elementGuidId>
    <imagePath></imagePath>
    <name>label_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/community-hs[1]/div[1]/section[1]/app-health-screening[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="\\35 \\.1"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:text=\\"KOSPEN Community\\"i"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>