<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>42bb5b7d-aa3f-481b-81a1-e6e74a1e31e0</elementGuidId>
    <imagePath></imagePath>
    <name>input_confirmicorpassport</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/hiv-hs[1]/div[1]/section[1]/app-health-screening[1]/div[2]/div[2]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#confirmIcOrPassport</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'confirmIcOrPassport') and equals(@type,'password')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder="Confirm IC Number"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>confirmIcOrPassport</value>
        <webElementGuid>8cc58e3e-b39a-4497-ada5-dd3f2824e9e9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>password</value>
        <webElementGuid>8cc58e3e-b39a-4497-ada5-dd3f2824e9e9</webElementGuid>
    </webElementProperties>
</WebElementEntity>