<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bb606420-801b-456f-8d22-12653681125b</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-hajj-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/app-hajj-register-patient[1]/div[1]/form[1]/div[1]/div[1]/div[17]/div[2]/ng-select[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-select-multiple\\ ng-select-searchable\\ ng-select-clearable\\ ng-select\\ ng-untouched\\ ng-pristine\\ ng-valid\\ ng-select-focused\\ ng-select-opened\\ ng-select-bottom"] &gt; [class="ng-select-container\\ ng-appearance-outline\\ ng-has-value"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Select Comorbidities Present\xd7NA\xd7"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>