<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b9fce200-361d-468c-89d6-bd1bfd79f7d1</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-hajj-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/app-hajj-register-patient[1]/div[1]/form[1]/div[1]/div[1]/div[17]/div[2]/ng-select[1]/ng-dropdown-panel[1]/div[1]/div[2]/div[3]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#aebb87f931c1-2 &gt; [class="checkbox-container\\ ng-star-inserted"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=option[name="Hypertension"i] &gt;&gt; div &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>