<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7974f497-0a33-4625-a79e-0fe34ed4f5dd</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_health_screening</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-hs[1]/div[1]/app-sidebar[1]/section[1]/nav[1]/ul[1]/li[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="menu-item"]:nth-child(7) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Health Screening')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^Health Screening$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Health Screening</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
</WebElementEntity>