<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>42efb5f0-0f2a-420b-b767-d2943c5bf565</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-hajj-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/app-hajj-assessments[1]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[1]/td[6]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="p-3\\ border\\ rounded\\ mb-3\\ ng-star-inserted"] &gt; [class="radioTable\\ ng-star-inserted"] [class="ng-star-inserted"]:nth-child(6) &gt; [type="radio"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=row[name="How often do you consume"i] &gt;&gt; internal:role=radio &gt;&gt; nth=4</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
</WebElementEntity>