<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2039e4d8-66fa-4de1-ab27-8494d2612bd4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_hajj_pilgrim_health_examination</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/hiv-hs[1]/div[1]/app-sidebar[1]/section[1]/nav[1]/ul[1]/li[8]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="menu-item"]:nth-child(8) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Hajj Pilgrim Health Examination')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="Hajj Pilgrim Health"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Hajj Pilgrim Health Examination</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
</WebElementEntity>