<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d2be8339-9083-4bce-92d8-e21a5a40b882</elementGuidId>
    <imagePath></imagePath>
    <name>select_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-hs[1]/div[1]/section[1]/div[1]/app-screening-records[1]/div[3]/div[1]/div[1]/div[2]/div[1]/app-date-filters[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-control\\ form-control-sm\\ ng-untouched\\ ng-valid\\ ng-dirty"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>app-date-filters &gt;&gt; internal:role=combobox</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>