<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f3263ffe-00a7-4751-b23a-2e763cd86f98</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_10</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/community-hs[1]/div[1]/section[1]/app-health-screening[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[5]/div[1]/ng-select[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-select\\ ng-select-searchable\\ ng-select-clearable\\ ng-select\\ ng-select-single\\ ng-valid\\ ng-touched\\ ng-dirty\\ ng-select-focused\\ ng-select-opened\\ ng-select-top"] &gt; [class="ng-select-container\\ ng-has-value"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Select District\xd7Lundu \xd7"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>