<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6cd271b2-d65a-43b6-a37b-b0b4e14c6bcf</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_12</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/community-hs[1]/div[1]/section[1]/app-health-screening[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[3]/div[1]/ng-select[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-select\\ ng-select-searchable\\ ng-select-clearable\\ ng-select\\ ng-select-single\\ ng-valid\\ ng-touched\\ ng-dirty\\ ng-select-focused\\ ng-select-opened\\ ng-select-bottom"] &gt; [class="ng-select-container\\ ng-has-value"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="select ministry\xd7KEMENTERIAN PERUMAHAN DAN KERAJAAN TEMPATAN MALAYSIA (KPKT)\xd7"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>