<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>836fa2ce-b5df-43f5-9caf-e427d7d4fa9f</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[5]/form[1]/community-observation[1]/div[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-control\\ ng-untouched\\ ng-pristine\\ ng-valid\\ ng-star-inserted"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'number')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text=/^HeightcmWeightkgWaistlinecm$/ &gt;&gt; internal:role=spinbutton &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>number</value>
        <webElementGuid>2ceda3b4-330d-4cb5-bc84-7ebf38bc282b</webElementGuid>
    </webElementProperties>
</WebElementEntity>