<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0f42482-cf20-41ab-a046-3a88438851cc</elementGuidId>
    <imagePath></imagePath>
    <name>input_2_3_1_1_1_9</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[4]/form[1]/community-assessments[1]/div[1]/div[2]/div[1]/div[4]/div[9]/span[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\\32 _3\\.1\\.1\\.1\\.9</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'2_3.1.1.1.9') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Yes, during the last year"i &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>2_3.1.1.1.9</value>
        <webElementGuid>2ceda3b4-330d-4cb5-bc84-7ebf38bc282b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>2ceda3b4-330d-4cb5-bc84-7ebf38bc282b</webElementGuid>
    </webElementProperties>
</WebElementEntity>