<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5fb145fb-1a8b-47e0-9f68-27e091c7f795</elementGuidId>
    <imagePath></imagePath>
    <name>input_chkvalidate</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[1]/form[1]/community-register-patient[1]/div[1]/form[1]/div[1]/div[1]/div[19]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#chkValidate</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'chkValidate') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="I have verified that all the"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>chkValidate</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
</WebElementEntity>