<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3499f832-5b3a-4e82-96ef-36fec1082408</elementGuidId>
    <imagePath></imagePath>
    <name>input_0_3_1_1_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[4]/form[1]/community-assessments[1]/div[1]/div[2]/div[1]/div[3]/span[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\\30 _3\\.1\\.1\\.1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'0_3.1.1.1') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span &gt;&gt; internal:has-text="NeverOnce a month2-4 times a"i &gt;&gt; internal:label="Never"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>0_3.1.1.1</value>
        <webElementGuid>2ceda3b4-330d-4cb5-bc84-7ebf38bc282b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>2ceda3b4-330d-4cb5-bc84-7ebf38bc282b</webElementGuid>
    </webElementProperties>
</WebElementEntity>