<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae71afab-f395-4488-a6a1-d66554bb3fd8</elementGuidId>
    <imagePath></imagePath>
    <name>input_1_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[2]/form[1]/community-assessments[1]/div[1]/div[2]/div[1]/div[1]/span[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-check\\ form-check-inline\\ ng-star-inserted"]:nth-child(2) &gt; #\\31 \\.1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'1.1') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=radio &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>1.1</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>c5c590fe-7547-444c-9f0b-a240d127757c</webElementGuid>
    </webElementProperties>
</WebElementEntity>