<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a98f9719-c310-4be8-8364-b41997c4ca6c</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/div[1]/div[1]/div[1]/mat-option[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#mat-option-0 &gt; [class="mat-option-text"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Male"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>