<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>008f1e7c-14c1-42d5-8dcc-907b70c4e387</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/add-community-health-screening[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[6]/form[2]/community-observation[1]/div[1]/div[2]/div[3]/ng-select[1]/ng-dropdown-panel[1]/div[1]/div[2]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#a619b5202bf6-0 &gt; [class="ng-option-label\\ ng-star-inserted"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="AIDS ACTION RESEARCH GROUP ("i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>