<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e23bde44-7130-48c9-aec9-152c188766fb</elementGuidId>
    <imagePath></imagePath>
    <name>button_preview_before_submit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[9]/form[1]/app-recommendations[1]/div[3]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>app-recommendations [class="btn\\ btn-primary\\ px-4\\ mr-2"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Preview before Submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=button[name=\\"Preview before Submit\\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Preview before Submit</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
</WebElementEntity>