<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9046c7db-92cc-4658-ade1-dd4e443b64ef</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[1]/form[1]/app-register-patient[1]/div[1]/form[1]/div[1]/div[1]/div[11]/div[1]/div[2]/div[1]/ng-select[1]/ng-dropdown-panel[1]/div[1]/div[2]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#acecebf81d6c-0</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=option[name=\\"FATIMA AZ-ZAHRA\\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>