<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>194159ce-4e23-45b0-9b35-fe9bce3a1458</elementGuidId>
    <imagePath></imagePath>
    <name>input_7_2_1_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[9]/form[1]/app-recommendations[1]/div[1]/div[4]/div[1]/div[1]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\\37 \\.2\\.1\\.2</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'7.2.1.2') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:label=\\"Smoking cessation\\"i"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>7.2.1.2</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
</WebElementEntity>