<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5a56c3cf-d823-44e8-a4cf-d01b5bc7bbf7</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[3]/form[1]/app-assessments[1]/div[1]/div[3]/div[2]/table[2]/tbody[1]/tr[1]/td[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="radioTable\\ ng-star-inserted"]:nth-child(4) [class="ng-star-inserted"]:nth-child(2) &gt; [type="radio"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=row[name=\\"Little interest or pleasure in doing things.\\"i] &gt;&gt; internal:role=radio &gt;&gt; nth=0"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>6203fca8-f0e6-40e8-a145-56effc4beda9</webElementGuid>
    </webElementProperties>
</WebElementEntity>