<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fb65d6b2-7a2d-4a4b-af16-383c1160b768</elementGuidId>
    <imagePath></imagePath>
    <name>input_8_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[7]/form[1]/app-observation[1]/div[1]/div[3]/div[2]/div[4]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\\38 \\.4</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'8.4') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id="\\38 \\.4"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>8.4</value>
        <webElementGuid>203a3707-bed2-4238-b87f-c355bcef998a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>203a3707-bed2-4238-b87f-c355bcef998a</webElementGuid>
    </webElementProperties>
</WebElementEntity>