<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6730c333-1ce9-4fd8-ba43-f958024a5450</elementGuidId>
    <imagePath></imagePath>
    <name>label_object_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[1]/form[1]/app-register-patient[1]/div[1]/form[1]/div[1]/div[1]/div[11]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-group\\ row"]:nth-child(11) &gt; [class="col-sm-4"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:text=\\"Secondary School Details:\\"i"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>