<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>df493bb0-84a2-4cd9-bcdc-5a42187033d1</elementGuidId>
    <imagePath></imagePath>
    <name>ol_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-hs[1]/div[1]/section[1]/div[1]/app-health-screening[1]/nav[1]/ol[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="breadcrumb"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="HomeAdd New Health Screening"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>