<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>62b9aa09-ba9f-4a98-9361-bc6669dade36</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[1]/div[1]/mat-option[4]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#mat-option-7 &gt; [class="mat-option-text"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="TECHNICIANS AND ASSOCIATE"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>