<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0f4b1e0f-433c-44d0-8a79-8f706cc260d1</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/mat-dialog-container[1]/app-add-health-screening[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/mat-stepper[1]/div[2]/div[9]/form[1]/app-recommendations[1]/div[1]/div[4]/div[2]/textarea[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-control\\ mt-2\\ ng-untouched\\ ng-pristine\\ ng-valid"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>textarea</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>